export enum ActionType {
    ADD_USERS,
    RECEIVED_USERS,
    SET_CURRENT_USER_ID,

    // Error -->
    SET_HAS_ERROR,
    SET_ERROR_TITLE,
    CLEAR_ERROR_TITLE,
    SET_ERROR_MESSAGE,
    CLEAR_ERROR_MESSAGE,
    // <-- end

    // WhatsNew -->
    SET_LATEST,
    SET_SKIP_WHATS_NEW,
    SET_TAKE_WHATS_NEW,
    SET_PAGE_WHATS_NEW,
    SET_TOTAL_PAGES_WHATS_NEW,
    // <-- end

    // Images -->
    SET_IMAGES_OWNER,
    RECIEVED_USER_IMAGES,
    SET_SELECTED_IMG,
    ADD_IMAGE,
    REMOVE_IMAGE,
    ADD_SELECTED_IMAGE_ID,
    REMOVE_SELECTED_IMAGE_ID,
    CLEAR_SELECTED_IMAGE_IDS,
    INCR_IMG_COMMENT_COUNT,
    DECR_IMG_COMMENT_COUNT,
    // <-- end

    // Users -->
    ADD_USER,
    // <-- end

    // Forum -->
    SET_POST_COMMENTS,
    UPDATE_THREAD_TITLE,
    ADD_THREAD_TITLE,
    SET_THREAD_TITLES,
    SET_TOTAL_PAGES_THREADS,
    SET_PAGE_THREADS,
    SET_SKIP_THREADS,
    SET_TAKE_THREADS,
    SET_SELECTEDTHREAD_ID,
    SET_POST_CONTENT,
    // <--

    // status -->
    SET_USED_SPACE_KB,
    SET_TOTAL_SPACE_KB,
    // <-- end
}